---
latitude: 52.070375
longitude: -9.574189
name: Innisfallen Hotel
email: reservations@Hotelkillarney.ie
phone_number: 353-46-6623600
address:
  street1: Fossa
  street2: Co. Kerry
  state: ''
  city: Killarney
  country: 
  zip_code: V93CR90
_hotel_id: IRETIK
_portal_id: innisfallenhotel
_root_path: https://rt3api-prd.ttaws.com
logo: <img id="1500319497457" class=" " src="https://cdn.staging-traveltripper.info/site-assets/1_529_622/media/2017-07-17-151840/logo.jpg"
  />
